This directory contains the files to spike a reproducible config of my Linux
system.

Bash script =./run-container.sh= starts a Guix container for that config. It
uses the Guix version specified by =channel-specs.scm= and installs the packages
specified by =manifest.scm=.

In the container, you should clone my =system-spike= Git repository (preferable)
to =$HOME/repos/swinkels/system-spike=, with =$HOME= the home directory of the
user in the container. This repository contains the dotfiles for my Linux system
and several Git repositories that my setup depends on. If you then install them
=stow=, for example like this,
#+begin_example                                                                                                                                           |
 ~/repos/swinkels/system-spike on  system-spike [!?] via 🐃                                                                                               |
 ➜ stow --dir=$(pwd) --target=$HOME --verbose .                                                                                                            |
#+end_example
you should end up with a fully functional systems. File =notes.org= in the
=system-spike= repository contains more information about this setup.

The home directory in the container is directory
=$HOME/guix-container-homes/system-spike= of the host machine.

* Footnotes

[fn:1] For details, see the section on [[https://guix.gnu.org/cookbook/en/html_node/Reproducible-profiles.html][reproducible profiles]] in the Guix
cookbook.
