CONTAINER_HOME := ${HOME}/tmp/guix-container-homes/baringa

.PHONY: all nothing

all: nothing

nothing:
	# All further configuration has to be done from inside the container. In the
	# container, do the following:
	#
	# - cd ~/provisioning
	# - make
